server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_app
    username: postgres
    password: "#Placed@73"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

security:
  jwt:
    secret: ${JWT_SECRET:b3a9f4e19e9f0fbb4c9d1d9c53aefc77f9f8c0f0a3e7c0d7c4f6a1d3b9e4f1c8}
    issuer: ${JWT_ISSUER:api.projects.ranjankr73}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}